package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Comp_Dep'
in the project with id = 'Comp', and delete the patch script.
*/
create(RelativeId("Comp"), BuildType({
    id("Comp_Dep")
    name = "dep"

    vcs {
        root(RelativeId("HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup"))
    }

    steps {
        gradle {
            tasks = "clean build"
            gradleWrapperPath = ""
        }
        script {
            scriptContent = "sleep 60"
        }
    }
}))

